version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zoo
    ports:
      - "3181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      confluent:
        aliases:
         - zoo

  kafka:
    image: confluentinc/cp-enterprise-kafka
    hostname: kafka
    depends_on:
      - zookeeper
      - c3_kafka
    ports:
      - "9096:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "c3_kafka:9092"
    networks:
      confluent:
        aliases:
         - kafka

  c3_zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: c3_zoo
    ports:
      - "4181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      confluent:
        aliases:
         - c3_zoo

  c3_kafka:
    image: confluentinc/cp-enterprise-kafka
    hostname: c3_kafka
    depends_on:
      - c3_zookeeper
    ports:
      - "9097:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "c3_zoo:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_METRIC_REPORTERS: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
      KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: "localhost:9092"
    networks:
      confluent:
        aliases:
         - c3_kafka

  c3:
    image: confluentinc/cp-enterprise-control-center
    hostname: c3
    depends_on:
      - c3_kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: "c3_zoo:2181"
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "c3_kafka:9092"
      CONTROL_CENTER_REPLICATION_FACTOR: "1"
    networks:
      confluent:
        aliases:
         - c3

 
networks:
  confluent:

